name: amplify_trips_planner
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  amplify_api: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0

  amplify_flutter: ^1.0.0
  amplify_storage_s3: ^1.0.0
  aws_common: ^0.5.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  go_router: ^7.0.0
  image_picker: ^0.8.0
  intl: ^0.18.0
  file_picker: ^5.0.0
  path: ^1.8.3
  timelines: ^0.1.0
  url_launcher: ^6.1.5  
  uuid: ^3.0.7
  riverpod_annotation: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  amplify_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5

flutter:
  uses-material-design: true
  assets:
    - images/amplify.png